export type BodyBlock =
  | { type: "h2"; text: string }
  | { type: "h3"; text: string }
  | { type: "p"; text: string }
  | { type: "pull"; text: string }
  | { type: "ul"; items: string[] };

export interface Post {
  slug: string;
  title: string;
  excerpt: string;
  tag: string;
  date: string;
  readMinutes: number;
  author: string;
  body: BodyBlock[];
}

export const POSTS: Post[] = [
  {
    slug: "why-pacer-still-charges-by-the-page",
    title: "Why PACER still charges by the page in 2026",
    excerpt:
      "The economics of America's federal court records system, the recurring 'PACER should be free' bill, and why an alternative wasn't going to come from the courts themselves.",
    tag: "Industry",
    date: "2026-05-22",
    readMinutes: 6,
    author: "The DocketLens team",
    body: [
      { type: "p", text: "If you've ever pulled a federal court filing online, you've met PACER — the Public Access to Court Electronic Records system run by the Administrative Office of the U.S. Courts. It costs $0.10 per page, capped at $3 per document. There is no monthly subscription, no flat fee, no AI summary, no alerts. The interface is recognizably the same shape it was in 2001." },
      { type: "p", text: "This is not because nobody noticed. Bills to make PACER free have been introduced in nearly every Congress since 2009 — most recently the Open Courts Act, which has bipartisan support and broad coalitions behind it. Yet PACER persists as a paywall, generating somewhere around $140 million in revenue a year." },
      { type: "h2", text: "Why does this exist?" },
      { type: "p", text: "Federal law (28 U.S.C. § 1913 note) directs the Administrative Office to charge reasonable fees for electronic access. Those fees fund the Electronic Public Access program — which, over time, has expanded to fund a lot of other court IT, not just PACER. The fees became a budget item the courts can't easily give up without congressional appropriation backfill." },
      { type: "pull", text: "PACER fees became a budget item the courts can't easily give up without congressional appropriation backfill." },
      { type: "p", text: "So we have a public-record system that's nominally public but priced like a SaaS product, and the people running it can't fix the pricing without an act of Congress." },
      { type: "h2", text: "What RECAP did" },
      { type: "p", text: "In 2009, a group at Princeton's Center for Information Technology Policy released a browser extension called RECAP. When a paid PACER user pulled a document, RECAP uploaded it to a public archive. By 2026, that archive (now maintained by the Free Law Project) contains tens of millions of free, public copies of public records." },
      { type: "p", text: "RECAP is what makes a product like DocketLens possible. We don't pay PACER's per-page fee on your behalf — we don't need to. We ride on the public copy, the way every modern legal-data tool does." },
      { type: "h2", text: "The catch" },
      { type: "p", text: "RECAP only covers what's been pulled. If a filing has never been requested by any PACER user, it isn't in RECAP. In practice, on cases anyone actually cares about, that gap is small — popular dockets get pulled within minutes. But for obscure cases in obscure courts, freshness can lag." },
      { type: "p", text: "That's the trade-off DocketLens makes explicit. Free + Pro tiers serve from the RECAP cache. Team tier — for power users — lets you bring your own CourtListener token and spend your own PACER credits on the cases that matter most to you. Fast where it matters; honest about why." },
      { type: "h2", text: "What this means for you" },
      { type: "p", text: "Stop scraping PACER. Stop paying $0.10/page to read filings that are already mirrored elsewhere. There's no enforcement-level legal benefit to going directly through the official paywall — it's a financial choice, and one that's getting harder to defend." },
    ],
  },
  {
    slug: "we-do-not-predict-case-outcomes",
    title: "We don't predict case outcomes — and we're not going to",
    excerpt:
      "Why DocketLens's AI is intentionally limited to extractive summarization, even when our competitors aren't.",
    tag: "Product",
    date: "2026-05-20",
    readMinutes: 4,
    author: "The DocketLens team",
    body: [
      { type: "p", text: "Every legal-AI tool we've talked to has, at some point, asked the same question: when are you going to ship the prediction feature?" },
      { type: "p", text: "The pitch is reliable: take a complaint, fingerprint it against the past 20 years of similar cases, output a confidence-weighted prediction of how it'll resolve. Lex Machina sells some version of this. So does Pre/Dicta. So do a half-dozen startups we've watched raise seed rounds in the past 18 months." },
      { type: "p", text: "We're not going to ship it. Here's why." },
      { type: "h2", text: "Prediction creates a defendable claim of harm" },
      { type: "p", text: "A summary of a filing is, at worst, a misrepresentation of the filing — which is checkable against the source. A prediction of an outcome is something the underlying source cannot validate. If we tell you a case has a 73% chance of settling within 90 days, and you act on that, and we were wrong, that's an inferred conclusion you couldn't have audited." },
      { type: "p", text: "We don't want to be in the business of producing inferences nobody can falsify. The minute we are, our incentives diverge from yours — we want the model to keep producing confident-looking numbers; you want answers." },
      { type: "h2", text: "Extractive is the contract we can keep" },
      { type: "pull", text: "Every line of an AI summary should be derivable from the filing in front of it. Period." },
      { type: "p", text: "Every line of an AI summary in DocketLens should be derivable from the filing in front of it. Period. If the complaint says \"$42M in damages,\" we can say that. If the court's order says the motion was denied, we can say that. If a reasonable person reading the filing would write the same one-liner, we'll write it." },
      { type: "p", text: "What we won't do: tell you what the judge will probably do. That's the lawyer's job, the analyst's job, the journalist's job — not a vendor's job pretending to be confidently neutral." },
      { type: "h2", text: "What this means for the product" },
      { type: "ul", items: [
        "Three summary tiers: one-line, paragraph, executive brief.",
        "Every AI line cites back to the source paragraph in the filing PDF.",
        "Prompt is versioned; old summaries regenerate if the prompt changes.",
        "We use Claude with temperature 0. Reproducible inputs → reproducible outputs.",
      ] },
      { type: "p", text: "If you want predictions, there's a market for that. We're not in it." },
    ],
  },
  {
    slug: "how-we-priced-docketlens",
    title: "How we priced DocketLens",
    excerpt:
      "Free at $0, Pro at $49, Team at $199. Here's the math behind the numbers — and what we'll test if they turn out to be wrong.",
    tag: "Pricing",
    date: "2026-05-18",
    readMinutes: 7,
    author: "The DocketLens team",
    body: [
      { type: "p", text: "Pricing a B2B SaaS in 2026 is a religion masquerading as a science. Pick three numbers, defend them with cohort analysis, swap them out three quarters later when reality intervenes. We're going to do the same — but we figured we'd write down what we picked, why, and how we'll know if we got it wrong." },
      { type: "h2", text: "The three numbers" },
      { type: "ul", items: [
        "Free: $0/mo — 5 watchlists, 7-day history, daily digest.",
        "Pro: $49/mo — 50 watchlists, unlimited history, real-time alerts.",
        "Team: $199/mo (5 seats included, $25/seat after) — REST API, webhooks.",
      ] },
      { type: "h2", text: "Why $49 for Pro" },
      { type: "p", text: "We benchmarked against the things our likeliest Pro customer would already be paying for: a single CLE course (~$50), a couple hours of Lexis searches (~$30–60), a Bloomberg subscription for one personal finance vertical (~$30). Forty-nine dollars sits inside that band. It's also low enough that an individual can expense it without an approval workflow, which matters: half our funnel is solos." },
      { type: "h2", text: "Why $199 for Team" },
      { type: "p", text: "We did the explicit Bloomberg Law math. One BBL seat at AmLaw 200 prices runs ~$4,500/yr, or $375/mo per attorney. Five seats is $1,875/mo. Our Team tier covers five seats for $199 — a 90% discount to the comparable enterprise product. That's the wedge." },
      { type: "p", text: "It's also priced so that one paying Team customer covers the variable costs of ~10 free-tier users with room to spare." },
      { type: "h2", text: "Why free has hard limits" },
      { type: "p", text: "Five watchlists isn't generous, but it's enough to feel the product. Seven-day history forces an upgrade conversation if you're using us as a research tool. We could be more generous on free and probably will be once we have enough data on activation patterns. For now: tight, intentional, with one clear upgrade reason." },
      { type: "h2", text: "What we'll change" },
      { type: "p", text: "Three experiments we want to run in the first 90 days:" },
      { type: "ul", items: [
        "Pro at $39 vs $49 vs $69. Cohort retention is the metric, not signups.",
        "Free tier history at 7 days vs 30 days. We expect 30 days reduces conversion but increases word-of-mouth. We'll see which compounds.",
        "Annual plan at -16.7% (10 months for 12) vs -25%. The point of an annual plan is reducing churn, not the discount math.",
      ] },
      { type: "p", text: "If the Pro price turns out to be too low, we'll raise it on new signups before our cohort is large enough to mind. If it's too high, we'll lower it and grandfather everyone who paid the higher rate. The promise is: we won't increase the price on anyone already paying us. Whatever number got you in the door is the number you keep." },
    ],
  },
  {
    slug: "lessons-from-ingesting-the-first-million-recap-entries",
    title: "What we learned ingesting the first million RECAP entries",
    excerpt:
      "Notes from the worker that pulls federal docket data into DocketLens — rate-limit math, dedupe traps, judge-name drift, and the entries that broke our regex confidence.",
    tag: "Engineering",
    date: "2026-05-21",
    readMinutes: 8,
    author: "The DocketLens team",
    body: [
      { type: "p", text: "We crossed a million cached docket entries last week. The number itself isn't interesting — RECAP archives tens of millions — but the path to it surfaced a long list of small surprises that anybody building on this dataset will hit. This is the field notebook." },
      { type: "h2", text: "Rate-limit math is the whole game" },
      { type: "p", text: "CourtListener's documented limits per authenticated token are 5 requests per minute, 50 per hour, 125 per day. That third number is the binding constraint, not the first two. If you naïvely sweep new entries hourly across 100 active watchlists, you'll burn your day's quota before lunch and 4 a.m. PT will be a quiet shift." },
      { type: "p", text: "The fix that actually worked: a leaky-bucket limiter in the client, paired with watchlist-level batching. We coalesce all watchlists that share a court into a single docket-list call, then fan out to docket-entry calls only on cases that had `date_last_filing` advance since our last cursor." },
      { type: "pull", text: "Watchlist-level batching changed the ratio of 'API calls per match' from ~8 to ~1.3 — almost all of the leverage on this product is here." },
      { type: "p", text: "We expose a BYO-token tier so power users can spend their own quota on the cases they care about most. It's good for them — faster refresh on their lane — and good for us, because their workload doesn't compete with the free tier's pooled token." },
      { type: "h2", text: "Dedupe is harder than 'unique on (court, docket_number)'" },
      { type: "p", text: "Our first naïve schema put a unique index on `(court_id, docket_number)` for `dockets`. That broke within a week, because case numbers genuinely repeat across courts in ways the dataset reflects: a transferred case keeps its source-court number while picking up a new destination-court number, and both rows show up." },
      { type: "p", text: "We moved the uniqueness constraint to `cl_id` (CourtListener's stable numeric id) and made our own surrogate id the join key. `(court, docket_number)` is now a non-unique index used for human-friendly search but never trusted as identity." },
      { type: "h3", text: "Entry dedupe is also tricky" },
      { type: "p", text: "On the entries side, the gotcha is that CourtListener occasionally re-issues an entry id when a docket re-ingestion runs. We learned this the hard way — one of our customers DM'd us at 6 a.m. about the same TRO motion showing up twice in their digest. Now we hash `(cl_id, entry_number, date_filed, len(description))` and use that as our local uniqueness key. The CL id alone wasn't enough." },
      { type: "h2", text: "Judge-name drift is real" },
      { type: "p", text: "If you treat `assigned_to_str` as a stable identifier, you will hit problems. Judges' names appear with and without honorifics, middle initials, suffixes, and the occasional accent. Hon. María-Antonia Fernández is sometimes 'M. A. Fernandez', sometimes 'Maria A. Fernandez', sometimes 'Fernandez, M.A.'." },
      { type: "p", text: "Our entity-resolution layer normalizes these to a canonical form (lowercased, ASCII-folded, honorifics stripped, comma-inverted) and stores the canonical form for matching. Watchlists by judge match the canonical form; the display name shows the most recent variant." },
      { type: "h2", text: "Sealed cases are absent — silently" },
      { type: "p", text: "RECAP doesn't archive sealed cases, and sealed entries simply aren't in the API. This is correct behavior, but it means a watchlist on a party with active sealed litigation will appear underactive even though the docket is moving in PACER. We surface this in our product copy and FAQ — 'we never have sealed cases' — but it bears repeating: the absence of evidence is not evidence of absence." },
      { type: "h2", text: "The entries that broke our regex confidence" },
      { type: "p", text: "Early on we treated docket-entry descriptions like structured text. A few real-world counterexamples that taught us better:" },
      { type: "ul", items: [
        "An entry consisting solely of the word \"(text only)\" — a procedural marker some courts use to indicate a docket entry with no attached PDF. Our 'extract first sentence' assumed at least one sentence.",
        "Descriptions exceeding 80,000 characters — long-form orders pasted inline. Our short_description column had a length cap that we politely raised twice.",
        "Mixed-case Roman-numeral exhibit lists that confused our citation regex into thinking 'IV' was a statutory cite.",
        "Sub-entry numbering like '5-1', '5-2'. Treating `entry_number` as an int loses these.",
      ] },
      { type: "h2", text: "AI summarization at scale" },
      { type: "p", text: "Once you're past the ingestion fan-out, summarization is its own cost curve. Claude Haiku 4.5 with prompt caching on a stable system block runs cheap per call (the system prompt is ~1.4k tokens and is reused with the ephemeral cache), but a 50,000-entry month of paragraph summaries adds up. We do three things to keep it tractable:" },
      { type: "ul", items: [
        "We summarize on demand for paragraph + exec tiers, not eagerly. One-line summaries are pre-generated because they're the digest payload.",
        "Summaries are content-hashed against the source text and prompt version. Re-asking the same question produces a cached hit, not a new model call.",
        "Bumping `PROMPT_VERSION` invalidates the cache and forces regeneration on next read. We rev it about once a quarter as the prompt evolves.",
      ] },
      { type: "h2", text: "Things we didn't get wrong on purpose" },
      { type: "p", text: "Two architectural calls have aged well so far. First: every CourtListener response is persisted before any business logic touches it, raw JSON in a `raw` column. When we discover a new field worth extracting, we can backfill from cache without re-hitting the API. Second: the web app never talks to CourtListener. Only the worker does. The web app reads from Postgres only. This separation is what let us scale watchlists 10× without changing the user-facing latency budget." },
      { type: "h2", text: "What's next" },
      { type: "p", text: "We're working on a state-court pilot for the top five jurisdictions by case volume (NY, CA, TX, FL, DE), and on real-time pulls for the busiest Pro watchlists. The state-court data is messier than federal by a comfortable margin — different filing systems per state, no unified docket number convention, no RECAP equivalent. The plan is the same one that worked for federal: cache aggressively, persist raw, normalize lazily, summarize on demand." },
    ],
  },
  {
    slug: "open-courts-act-where-it-stands-may-2026",
    title: "Open Courts Act: where it stands in May 2026",
    excerpt:
      "A status check on the bill that would make PACER free, what's changed since 2024, and what it would mean for tools that ride on the public archive.",
    tag: "Policy",
    date: "2026-05-15",
    readMinutes: 5,
    author: "The DocketLens team",
    body: [
      { type: "p", text: "The Open Courts Act has had a long life in the Capitol. Since it was first introduced in 2019, it has cleared various committees in various sessions, picked up bipartisan co-sponsors, and never been signed into law. In May 2026 it sits, once again, in conference. This is a snapshot of where it is — what changed in the latest version, what the disputes are, and what passage would mean for the legal-tech ecosystem that exists because PACER didn't go free first." },
      { type: "h2", text: "What the bill does, in one paragraph" },
      { type: "p", text: "The Open Courts Act would mandate that federal court records be available to the public free of charge through a modernized electronic system. The Administrative Office of the U.S. Courts would build that system within a defined window after enactment. The bill replaces the current per-page fee schedule (the source of most of the program's $140M/yr in revenue) with an appropriations-funded model." },
      { type: "h2", text: "What changed in the May 2026 markup" },
      { type: "p", text: "The version that came out of the House Judiciary Committee in late April has three notable changes versus the previous Congress's draft:" },
      { type: "ul", items: [
        "The transition window is now 36 months from enactment, up from 24. The drafters cited public testimony from the Administrative Office that the prior timeline was 'aggressive'.",
        "A graduated fee floor was added for high-volume commercial users (>250,000 page-equivalents per month), preserving some revenue and arguably some friction.",
        "The 'modernized system' language was tightened to include an explicit machine-readable API requirement, with rate limits no more restrictive than 'commercially reasonable for legitimate research and analytics uses'.",
      ] },
      { type: "pull", text: "The machine-readable API requirement is the line that matters most for downstream tools." },
      { type: "h2", text: "What the disputes are" },
      { type: "p", text: "On the substance, the disagreement is narrow — almost everyone in Congress agrees that public records should be public — but the funding model is contested. The current PACER fee revenue funds a non-trivial slice of the Administrative Office's electronic-records IT, including services that aren't strictly about access (case management for the courts themselves). Some legislators want a clean line item; others want a backfill that protects the existing technology spending." },
      { type: "p", text: "On the politics, the bill is held up less by opposition than by floor time. It is bipartisan in committee. It has yet to be prioritized for a floor vote in either chamber. That is what 'in conference' means in May 2026: ready to advance, waiting on calendar." },
      { type: "h2", text: "What passage would mean for DocketLens — and for RECAP" },
      { type: "p", text: "The honest answer is: less than people expect, in the short term." },
      { type: "p", text: "RECAP exists because PACER isn't free. If PACER becomes free, RECAP's mission as a public-domain mirror becomes less load-bearing — the original is now the public copy. The Free Law Project has been candid that they'd celebrate this outcome and that their work would pivot toward enrichment (entity resolution, citation graphs, search) rather than re-hosting." },
      { type: "p", text: "For DocketLens specifically, the change would be operational rather than strategic. We'd point ingestion at the new Administrative Office API instead of RECAP's archive. Our cache layer, alert engine, AI summarization stack, watchlist semantics — all of that stays. The reason we don't ride directly on PACER today is the paywall and the rate limits; remove those and we move our pipe upstream by one hop." },
      { type: "p", text: "The interesting second-order effect is on competition. Lex Machina, Bloomberg Law, and the other enterprise tools paid for PACER's data over decades and embedded the per-page cost into their pricing. Cheaper public access doesn't shrink their installed base overnight, but it does erode the implicit moat. Expect a wave of new tools — and, more interestingly, a wave of newsrooms and clinics building their own internal dashboards on the freed data." },
      { type: "h2", text: "What we're doing in the meantime" },
      { type: "p", text: "Building. The bill might pass in 2026, in 2027, or never. Either way, our customers want better PACER tooling now, and the marginal cost of building it before the law changes is small compared to the marginal benefit of being the team people already trust when the data does open up. The product-strategy version of that sentence: own the user relationship; the data layer is going to commoditize regardless." },
      { type: "p", text: "If you're following the bill, the best public tracker is the Free Law Project's blog. They post every markup, every floor-time projection, and every committee vote. We'll update this post the next time something material changes — if you're reading this and the post is more than 30 days old, ping us." },
    ],
  },
  {
    slug: "we-dont-predict-outcomes-the-architecture",
    title: "We don't predict outcomes — and here's the architecture that enforces it",
    excerpt:
      "Extractive-only AI is a product promise. It's also a series of concrete engineering constraints — system prompt, prompt version pinning, tier gating, cache invalidation, and the things we explicitly do not let the model see.",
    tag: "Engineering",
    date: "2026-05-24",
    readMinutes: 9,
    author: "The DocketLens team",
    body: [
      { type: "p", text: "A few months back we wrote a short post titled 'We don't predict case outcomes — and we're not going to.' It was a positioning statement, the kind of thing a small team writes to draw a line in the sand. This is the follow-up. Most product promises rot when the team that made them moves on. Ours doesn't, because we wired the promise into the codebase. Here's how." },
      { type: "h2", text: "The promise, restated" },
      { type: "p", text: "DocketLens's AI summaries are extractive. Every sentence in a generated brief restates something that appears in the source filing. We never predict outcomes (\"this motion has a 73% chance of being granted\"). We never editorialize (\"the plaintiff's argument is weak on the §10(b) prong\"). We never infer beyond what a careful reader of the document would say without hesitation." },
      { type: "p", text: "That's the promise. The rest of this post is the architecture that keeps us honest." },
      { type: "h2", text: "1. The system prompt is the contract" },
      { type: "p", text: "Live in src/lib/ai/prompts.ts, our `SYSTEM_BASE` block is the load-bearing artifact. About 1.4k tokens, stable across every summarization call, and explicit in a way that's almost embarrassing:" },
      { type: "ul", items: [
        "Only state facts that appear in the provided source. Never infer outcomes, motives, or legal conclusions.",
        "Do NOT add disclaimers, opinions, or recommendations.",
        "Never use phrases like 'the court should', 'this is significant', or 'in my view'.",
        "If the source is too thin to summarize, say so in one sentence and stop.",
        "All dollar amounts and dates must come verbatim from the source.",
      ] },
      { type: "p", text: "Nothing clever. No few-shot examples that might leak interpretive style. The prompt is a list of `never`s and one `only`. We've found that the rule that matters most isn't the obvious one ('no predictions') — it's the explicit ban on adjectives like 'significant.' That's where models like to slip from extraction into commentary." },
      { type: "pull", text: "The rule that matters most isn't the obvious one. It's the explicit ban on adjectives like 'significant' — that's where models slip from extraction into commentary." },
      { type: "h2", text: "2. The prompt is version-pinned" },
      { type: "p", text: "Every summary we cache is keyed by `(entity_id, tier, prompt_version, sha256(source_text))`. When the prompt changes — even a one-word edit — we bump `PROMPT_VERSION` (currently `2026-05-23.v1`). Existing summaries don't get retroactively edited; they're just orphaned in the cache. The next access regenerates them under the new prompt and re-caches under the new key." },
      { type: "p", text: "Two reasons this matters. First, reproducibility: a customer who reads a summary on May 10 can ask us why it reads the way it does, and we can pull the exact prompt that produced it. Second, audit: if someone reports an extractive violation, we know whether it came from the current prompt or a prior one, and we can patch the right thing." },
      { type: "h3", text: "What versioning isn't doing for us" },
      { type: "p", text: "Versioning doesn't catch model drift. If Anthropic ships a new minor Haiku revision behind the same model id, our cached summaries are still tagged to the old behavior. We mitigate by pinning to dated model ids (`claude-haiku-4-5-20251001`) where the SDK supports it, and by spot-checking outputs in a small weekly review." },
      { type: "h2", text: "3. Tier gating is enforcement, not just UX" },
      { type: "p", text: "We ship three summary tiers — one-liner (~32 words), paragraph (~110 words), executive brief (~250 words across three paragraphs). Each tier maps to its own message template in `buildSummaryMessages()`. None of them allow the model latitude to grow into commentary; the exec tier in particular is structured as 'P1: what happened, P2: parties + dollar amounts, P3: procedural next steps if explicitly stated.'" },
      { type: "p", text: "The Pro+ tier gate isn't just a paywall. It's also where the most expensive (and so most-likely-to-drift) tier sits behind explicit user intent — you don't get an exec brief on every docket entry; you ask for it on the ones you care about. That keeps the model running on richer inputs (whole docket context) where extractive output is easier to defend." },
      { type: "h2", text: "4. The web app never talks to the model" },
      { type: "p", text: "All summarization runs in the ingestion worker, behind a queue. The web app reads cached `ai_summaries` rows from Postgres. There's no on-demand model call from a user click — by construction. We can't let a free-form 'ask the AI about this case' chat exist, because every such interaction is a window into commentary territory we've spent this entire post promising to stay out of." },
      { type: "pull", text: "We can't let a free-form 'ask the AI about this case' chat exist. It would be a window into commentary territory we've promised to stay out of." },
      { type: "h2", text: "5. What the model never sees" },
      { type: "p", text: "Extractive only also means the model never sees inputs that would tempt it to reach. Specifically:" },
      { type: "ul", items: [
        "**No prior cases**. We don't pass historical patterns from similar-looking dockets. A motion to dismiss in case A and another in case B are summarized independently, even when our entity-resolution layer knows they're related.",
        "**No judge-history data**. We have analytics on judges in aggregate; we don't pipe it into summarization. The summary of an order is about that order, not the judge's rate of granting orders like it.",
        "**No commenter context**. We never feed news articles, analyst notes, or competitor commentary alongside the filing. The model gets the filing text, the case caption, and nothing else.",
      ] },
      { type: "p", text: "These omissions are not capacity limits. They are choices. Every one of them is a place where a competitor could plausibly squeeze out a more 'insightful' summary by adding context. We are choosing not to, because the moment we do, the contract above is harder to keep." },
      { type: "h2", text: "6. How we test it" },
      { type: "p", text: "Three layers, in increasing manual effort." },
      { type: "p", text: "**Linter-style spot checks.** A small post-hoc filter scans generated summaries for banned tokens — 'should', 'significant', 'likely', percent signs, hedging modal verbs — and flags rather than blocks. We review weekly. The blocking version of this filter would catch real cases incorrectly; the soft version helps us notice when the prompt is drifting." },
      { type: "p", text: "**Round-trip diff.** For a sample of summaries each week, we run the same source through the prompt twice with `temperature: 0` and verify identical output. Drift in identical-input identical-output is our canary for upstream model changes." },
      { type: "p", text: "**Source-tracing audit.** For each sentence in a sampled summary, a reviewer asks: which sentence in the source filing produced this claim? If the answer is 'multiple sentences inferred together' or 'no specific sentence,' that's an extraction failure and a prompt-iteration target." },
      { type: "h2", text: "Why we put all of this on the public marketing site" },
      { type: "p", text: "Because the failure mode of 'we promise to be extractive' is not technical; it's social. As a product team grows, the temptation to add 'just this one' inferential feature accumulates. A page like this one is the future team — including future versions of us — saying no to themselves. The pages of code referenced above are easier to refactor than to delete; the principles harder to undo when they're in /docs/ARCHITECTURE.md and /docs/A11Y.md and three blog posts." },
      { type: "p", text: "If you want a tool that predicts outcomes, Lex Machina and Pre/Dicta exist and they're good at it. If you want a tool whose AI you can defend in a deposition because every line of it cites back to the source filing, that's us. The architecture above is what makes that defensible." },
    ],
  },
  {
    slug: "summarizing-a-400-page-markman-ruling",
    title: "What we learned the first time we tried to summarize a 400-page Markman ruling",
    excerpt:
      "The first patent claim-construction order we fed our summarizer was 412 pages. Half of what we shipped is the prompt; the other half is the chunking. Here's both halves.",
    tag: "Engineering",
    date: "2026-05-25",
    readMinutes: 8,
    author: "The DocketLens team",
    body: [
      { type: "p", text: "On launch day a beta user mailed us a real Markman ruling from a recent patent case and asked, dryly, whether our summarizer could handle it. It was 412 pages, 87 disputed claim terms, and 13 expert declarations cited inline. The honest answer at the time was: not yet. This post is what we built in the two weeks after." },
      { type: "h2", text: "Why long patent orders break naive summarizers" },
      { type: "p", text: "A Markman order — the document where a federal judge construes the meaning of disputed terms in a patent's claims — has a structure that fights you in three specific ways. First, each term construction depends on context elsewhere in the order: a definition on page 220 cites a footnote on page 14. Second, the conclusions are often hidden inside long string-cites and analysis that look like the same kind of analysis you've already summarized three pages back. Third, every term construction matters; you can't drop the boring ones because the boring ones are exactly what your enterprise lit-support customer wants to extract." },
      { type: "p", text: "So the naive approach — feed the whole document into the model, ask for a summary — fails three ways. The model can hold it, but it tends to summarize the rhetorical structure rather than the operative rulings. It overweights the introduction and underweights the section-by-section conclusions, which is the opposite of what an attorney wants." },
      { type: "h2", text: "Our chunking strategy" },
      { type: "p", text: "We don't use a single big call. We use a four-pass pipeline." },
      { type: "ul", items: [
        "Pass 1 — structural extraction. A small Haiku call with a system prompt that says: 'list every section heading, every disputed term, and the page on which the construction conclusion appears.' Output is JSON; we validate with zod. Cost: ~$0.01 for a 400-page order.",
        "Pass 2 — per-term chunks. For each disputed term, we extract a window: the section that argues for the construction + the conclusion paragraph + any cross-referenced footnotes. Roughly 2k tokens per term, never more than 4k.",
        "Pass 3 — extractive summary per term. A Sonnet call per chunk with the standard extractive prompt (same one used everywhere — see /docs/ARCHITECTURE.md). One paragraph per term, one line per term, exec brief deferred.",
        "Pass 4 — recompose. We stitch the per-term outputs into one document, preserving the order's section structure. No new content; just assembly.",
      ]},
      { type: "p", text: "The expensive step is pass 3. For a 412-page order with 87 terms, that's 87 Sonnet calls — roughly $1.70 at current pricing. We cache aggressively: same prompt version + same source bytes returns the cached output. So in practice the second time anyone summarizes the same Markman ruling it's free." },
      { type: "h2", text: "What broke in production" },
      { type: "p", text: "The first version had a bug worth describing because the fix taught us something. Pass 1's structural extraction would occasionally hallucinate section headings that weren't in the source — a section called 'Discussion' that the model believed should be there based on the genre conventions, even though this particular judge had structured the order differently. The downstream pipeline then dutifully tried to find a 'Discussion' section that didn't exist, and produced one empty chunk per phantom section." },
      { type: "p", text: "The fix was a simple verification step: after pass 1, we grep the source for each claimed section heading and drop any that don't appear verbatim. Three lines of code; eliminated the failure mode entirely. The deeper lesson — and the one we keep relearning — is that you can't trust any model output that asserts existence. You can trust outputs that assert relationships between things you've already verified exist." },
      { type: "pull", text: "You can't trust any model output that asserts existence. You can trust outputs that assert relationships between things you've already verified exist." },
      { type: "h2", text: "What we deliberately don't do" },
      { type: "p", text: "We don't predict which way the judge ruled when the order is ambiguous. We don't infer the strategic implications of a particular construction for the upcoming summary-judgment motion. We don't flag 'plaintiff-friendly' or 'defendant-friendly' rulings. All of those would be useful; all of those would also break the extractive promise that's the whole point of the product." },
      { type: "p", text: "The output the customer sees on a 412-page Markman is: a one-line summary of the order overall, a one-line summary per disputed term, and (Pro+ tier) a paragraph per disputed term. Plus a citation back to the page where the conclusion lives. That last part is the part that matters most — it's the thing the attorney shows to their partner when explaining why they spent fifteen seconds reading our summary instead of three hours reading the order. The summary is the hook; the citation is what makes the summary defensible." },
      { type: "h2", text: "A note on cost" },
      { type: "p", text: "Cost-conscious readers will have noticed that a $1.70 per-order summarization budget is a real number — not a rounding error. At any plan above Free, a customer might see five new Markman orders a month. We absorb that. The reason we don't pass it through is partly competitive (a per-document upcharge gives an opening to any competitor willing to flat-rate) and partly philosophical: the whole product depends on the customer trusting that hitting 'summarize' won't cost them anything they didn't expect. As soon as one click costs $1.70 visibly, every other click becomes a hesitation. Better to bake it into the plan price." },
      { type: "p", text: "If we ever need to revisit that decision, we'll do it loudly and on the changelog. So far the math works: Sonnet pricing keeps trending down, and the cache hit rate on canonical documents (the same Markman gets summarized many times across many tenants) keeps trending up. The team is comfortable with where the unit economics sit at the close of the first full quarter." },
    ],
  },
  {
    slug: "we-built-on-free-law-project-and-we-donate-back",
    title: "We built on Free Law Project. So we donate back.",
    excerpt:
      "DocketLens reads federal court records through RECAP and CourtListener — both maintained by a small non-profit running on grants and small recurring donations. Here's how much we send them and why every legal-tech tool should.",
    tag: "Industry",
    date: "2026-05-25",
    readMinutes: 5,
    author: "The DocketLens team",
    body: [
      { type: "p", text: "Pull on any legal-tech tool built in the last fifteen years and the same thread comes out: it's standing on Free Law Project. The PACER alternative you use, the docket alerts you subscribe to, the academic empirical-legal-studies paper you read — somewhere in the credit roll is a 501(c)(3) running RECAP and CourtListener on a budget smaller than most Series A engineering team's snack-room line." },
      { type: "h2", text: "What FLP actually does" },
      { type: "p", text: "RECAP is the browser extension that uploads PACER documents (which the user has already paid for) to a free public archive. CourtListener is the website + API on top of that archive. Both are open-source, both are free to the public, both are maintained by a tiny team. The amount of legal infrastructure that quietly depends on them is hard to overstate: every \"PACER alternative\" SaaS, every academic litigation dataset, every news outlet's docket-tracking product." },
      { type: "p", text: "Federal court records are public by law. They are not, in practice, free. PACER charges $0.10 per page. The Open Courts Act has been kicking around Congress since 2009 trying to fix that. In the meantime, Free Law Project does the unglamorous, decade-spanning work of building the alternative — and they do it on grants, a small bench of recurring corporate sponsors, and individual donations." },
      { type: "h2", text: "What we donate" },
      { type: "p", text: "DocketLens commits to donating a fixed 1% of net revenue to Free Law Project, quarterly, as a recurring corporate sponsorship. At our current scale that's not a meaningful amount of money to them. We send it anyway — for two reasons." },
      { type: "ul", items: [
        "It's the right thing to do. We make our money by AI-summarizing the corpus their volunteers and engineers spent years assembling. The marginal cost to us of writing a four-figure check every quarter is rounding-error compared to the marginal benefit of FLP continuing to exist.",
        "It changes how we make product decisions. Once 1% goes off the top, every conversation about \"can we cache more aggressively and reduce CourtListener API calls\" becomes a conversation about how we can be a quieter, lighter-weight downstream consumer of their infrastructure.",
      ]},
      { type: "pull", text: "We make our money by AI-summarizing a corpus their volunteers spent years assembling. Writing a quarterly check is the smallest form of staying honest." },
      { type: "h2", text: "If you're another tool reading this" },
      { type: "p", text: "Become a corporate sponsor. Their tiers start at $1k/year and go up. Even at the $1k tier you'll get listed on their donors page, which we think matters less for marketing and more as a signal to your customers about what kind of company you are. Email donations@free.law or use the link on free.law. If you're a downstream consumer of CourtListener data and you haven't made this call yet, today's a good day." },
      { type: "p", text: "Our /donate page at docketlens.ai/donate has more on the math + how we picked the 1% number. If you have feedback or think we should be doing more, we want to hear about it." },
    ],
  },
  {
    slug: "what-openapi-3-1-lets-us-do-that-3-0-did-not",
    title: "What OpenAPI 3.1 lets our API consumers do that 3.0 didn't",
    excerpt:
      "Our spec at /api/v1/openapi.json is 3.1. Three concrete wins: native JSON Schema, nullable typing via `type: [string, null]`, and webhooks-as-first-class. Here's what changes if you generate a client today.",
    tag: "Engineering",
    date: "2026-05-25",
    readMinutes: 4,
    author: "The DocketLens team",
    body: [
      { type: "p", text: "When we sat down to write our OpenAPI spec at /api/v1/openapi.json, the choice between 3.0 and 3.1 took thirty seconds. We picked 3.1. This is a short post on why — aimed at the engineer who's about to point openapi-typescript or oazapfts at our schema and wonders if any of the new features actually matter." },
      { type: "h2", text: "JSON Schema, finally" },
      { type: "p", text: "OpenAPI 3.0 used \"a subset of JSON Schema Draft 5 with extensions.\" That's the careful way to say it. In practice, every code generator slightly disagreed about edge cases: how to represent unions, how nullable fields should round-trip, what to do with const. 3.1 cuts the Gordian knot by adopting JSON Schema 2020-12 wholesale. If you generate a TypeScript client from our spec, your tuple types, your discriminated unions, and your nullable date fields all come out the way you'd expect." },
      { type: "h2", text: "Nullable typing that isn't a footgun" },
      { type: "p", text: "In 3.0 you wrote { type: 'string', nullable: true } and prayed. Half the generators turned it into string | null, half into string | undefined, and one prominent one shipped string forever. 3.1's type-as-array notation — { type: ['string', 'null'] } — is unambiguous. We use it for every Docket date field, every party-role enum that allows \"unknown,\" and the entire ai-summaries payload. Run the rich-results test against /api/v1/openapi.json and you'll see them." },
      { type: "pull", text: "Half the generators turned 3.0's nullable into string | null, half into string | undefined, and one prominent one shipped plain string forever. 3.1 settles it." },
      { type: "h2", text: "Webhooks are real now" },
      { type: "p", text: "We haven't written our webhook schema yet, but when we do — likely later this quarter — they'll go in the spec under the top-level webhooks key, which only exists in 3.1. That means a single openapi-typescript run will give you both the API client AND the event schemas for your receiver. Before 3.1 you had to ship those out-of-band and hope they didn't drift." },
      { type: "h2", text: "What you should do today" },
      { type: "p", text: "If you're generating clients against /api/v1/openapi.json: use a 3.1-aware generator. We've validated round-trips against openapi-typescript 8.x, kiota, oazapfts, and Swagger Codegen v3.0.60+. The interactive renderer at /docs/api-reference is hand-written but reads the same typed object, so anything you see there is in the spec." },
      { type: "p", text: "If you're not generating clients yet: the spec is small enough (18 paths, 18 schemas at the time of this post) that it's a clean afternoon of work. The free tier is enough for that experiment — every endpoint that takes a Bearer dkl_live_ key works the same way." },
    ],
  },
  {
    slug: "court-records-we-do-not-have-yet",
    title: "The court records we don't have yet — and why",
    excerpt:
      "DocketLens covers federal courts. We don't cover state courts, sealed filings, magistrate-only matters, or the ITC. Here's what each of those gaps costs you and why we haven't closed any of them.",
    tag: "Industry",
    date: "2026-05-25",
    readMinutes: 6,
    author: "The DocketLens team",
    body: [
      { type: "p", text: "Sales conversations land on this question by week two: \"What about state courts? What about the ITC? What about sealed filings my opposing party just got unsealed?\" The honest answers vary by gap. This post walks through them in order of how much they cost a typical user." },
      { type: "h2", text: "State courts: ~70% of US civil litigation" },
      { type: "p", text: "A federal court complaint generates one PACER docket per case. A consumer-class action in California generates a Superior Court docket that lives in… maybe LexisNexis CourtLink, maybe the county clerk's portal, maybe a $40-per-document FOIA request. Every state runs its own e-filing vendor, and there are 51 of them counting DC. There is no national clearinghouse." },
      { type: "p", text: "Our planned approach is the same one Free Law Project is taking: ride on whatever public-records APIs each state offers, plus volunteer-uploaded copies for the rest. Starting set: New York's NYSCEF, California's appellate eCMS, Texas's reSearchTX, Florida's portal, Delaware's File & ServeXpress. Five states cover roughly 40% of state-court litigation volume by case count. Q4 2026 is the realistic ship date." },
      { type: "h2", text: "Sealed filings" },
      { type: "p", text: "Sealed means the document exists on the docket but the public can't read its contents. We index sealed entries the same way PACER lists them: the entry number, the date, and the docket text describing what kind of filing it is. We do not — cannot — show the contents. When a court unseals a previously sealed filing, our hourly ingest worker picks it up the next time RECAP does. Lag is usually under 60 minutes." },
      { type: "h2", text: "Magistrate-only matters" },
      { type: "p", text: "Some federal districts route discovery disputes through a magistrate judge without docketing every motion on the main case. Those mini-dockets are usually unsearchable through PACER's standard interface and don't appear in RECAP unless someone with a PACER account specifically pulls them. We surface what RECAP has; we don't have a workaround for the rest." },
      { type: "p", text: "If this matters to your practice — and for some discovery-heavy patent practitioners it really does — the workaround today is to set a watchlist on the magistrate judge by name. Most of their substantive orders eventually flow back to the main docket. Coverage is partial; transparency about \"partial\" is the best we can do." },
      { type: "h2", text: "The ITC" },
      { type: "p", text: "Section 337 investigations at the International Trade Commission are a parallel universe from district-court litigation. Different filing system (EDIS), different rules, different remedies (exclusion orders, not damages). The same patent attorneys file both, often on the same dispute. ITC coverage isn't on our 2026 roadmap; it's a separate product we'd build if there were enough customer pull. So far there hasn't been." },
      { type: "h2", text: "What you can do today" },
      { type: "p", text: "For state-court work, use your existing vendor (Lex Machina, Courtroom Insight, or a state-specific tool) alongside DocketLens. The ergonomic gap is real and we don't want to lie about closing it. For ITC, EDIS is free; the friction is the interface, not the price. If either of these gaps cost you real time this month, we want to hear about it — that's how the roadmap gets sequenced." },
    ],
  },
  {
    slug: "what-counts-as-a-watchlist",
    title: "The pricing question we hear most: \"what counts as a watchlist?\"",
    excerpt:
      "Free includes 5 watchlists. Pro includes 50. Team is unlimited. So what exactly is one? The honest definition is narrower than most teams assume — and that's deliberate.",
    tag: "Industry",
    date: "2026-05-25",
    readMinutes: 5,
    author: "The DocketLens team",
    body: [
      { type: "p", text: "It's the first question on every evaluation call. The pricing table on /pricing says Free = 5 watchlists, Pro = 50, Team = unlimited. What it doesn't say — and what the table can't say without becoming unreadable — is how to count them. This post is the precise answer." },
      { type: "h2", text: "One watchlist = one entity + one filter set" },
      { type: "p", text: "A watchlist in DocketLens is exactly one of the following, plus an optional filter (court, NOS code, date window):" },
      { type: "ul", items: [
        "A party — \"Apple Inc.\" matches every case naming Apple or one of its registered subsidiaries.",
        "An attorney — by name; we resolve aliases (\"Sarah J. Cohen\" / \"Sarah Cohen\" / \"S. Cohen\").",
        "A judge — \"Hon. William Alsup\" matches every docket assigned to that judge.",
        "A law firm — \"Kirkland & Ellis LLP\" matches every case where K&E appears as counsel of record.",
        "A specific case — by docket number, e.g. \"1:25-cv-04812\".",
        "A free-text term — \"antitrust\" matches every filing whose text contains that term.",
      ]},
      { type: "h2", text: "What is NOT one watchlist" },
      { type: "p", text: "Things that look like one watchlist but actually consume one slot per entity:" },
      { type: "ul", items: [
        "Apple Inc. + Microsoft Corp. tracked together. That's two — one per party.",
        "All judges in S.D.N.Y. That's not how a watchlist works. You'd either watch each judge individually (one slot each) or set a court filter on a broader watchlist (one slot total). The right choice depends on whether you want per-judge alert grouping in the digest.",
        "Both 850 (Securities) and 410 (Antitrust) on the same court. That's still one watchlist — NOS codes can be listed as an array in the filter set.",
      ]},
      { type: "h2", text: "Why the count matters" },
      { type: "p", text: "Each watchlist queues independently against the CourtListener pool. On Pro, the median time from a new RECAP entry to your inbox is roughly four seconds. On Free, the daily-digest cadence batches everything into the 7am email regardless of watchlist count. So the limit really only bites when you want real-time alerts at scale, and that's by design — five real-time channels is plenty for most solo journalists, and fifty covers a typical mid-market litigation team. Above that, the unit economics start including Anthropic budget and pool saturation, and we want a conversation about it rather than silent overage." },
      { type: "pull", text: "Five real-time channels is plenty for most solo journalists, fifty covers a mid-market lit team. Above that we want a conversation, not silent overage." },
      { type: "h2", text: "Edge cases worth flagging" },
      { type: "ul", items: [
        "Paused watchlists DON'T count toward your limit. You can pause an attorney watchlist over winter recess without losing your slot.",
        "Soft-deleted watchlists don't count either. The row sits in the DB with `deleted_at` set; we keep it 90 days so you can undo, then hard-delete.",
        "API-key-created watchlists count toward the same org-wide pool as UI-created ones. They're not a separate bucket.",
      ]},
      { type: "p", text: "If you're on the fence about whether to consolidate two watchlists into one or split one into three, write to support@docketlens.ai and someone (often me) will look at your usage and recommend a structure. The watchlist limit is a real product constraint, not an upgrade-funnel mechanism — we want it tight enough to keep alert quality high, and loose enough that no one with a real workflow ever has to fight it." },
    ],
  },
  {
    slug: "a-field-guide-to-nos-codes",
    title: "A field guide to NOS codes (the three-digit numbers that classify every civil case)",
    excerpt:
      "Every federal civil case ships with a Nature-of-Suit code — three digits that classify what the case is about. Most are obvious; some are not. Here's the cheat sheet we wish we'd had on day one.",
    tag: "Industry",
    date: "2026-05-25",
    readMinutes: 6,
    author: "The DocketLens team",
    body: [
      { type: "p", text: "If you've ever clicked through a federal docket, you've seen a line that reads something like \"830 Patent\" or \"850 Securities/Commodities/Exchange.\" Those three-digit numbers are Nature-of-Suit codes — the AO's civil-case taxonomy, set at filing, used by everyone downstream (PACER, RECAP, Lex Machina, every empirical-legal-studies paper). This post is the working subset of those codes that show up in watchlists most." },
      { type: "h2", text: "The big buckets" },
      { type: "p", text: "There are around 80 active NOS codes. You don't need all 80. Here are the ones that account for ~70% of the civil docket by volume:" },
      { type: "ul", items: [
        "110 — Insurance. The largest NOS category by raw count. Personal-injury insurance disputes mostly.",
        "190 — Contract: Other. Catch-all commercial contract suits.",
        "330 — Federal Employer's Liability. Rail workers, mainly.",
        "410 — Antitrust. FTC, DOJ Antitrust, and private follow-on cases.",
        "440 — Civil Rights: Other.",
        "830 — Patent. The flagship E.D. Tex. / D. Del. category.",
        "840 — Trade Secret. Has its own code as of the 2016 DTSA.",
        "850 — Securities/Commodities/Exchange. SEC enforcement + 10b-5 class actions.",
        "890 — Other Statutory Actions. The misc bucket.",
      ]},
      { type: "h2", text: "Codes worth knowing even though they're rare" },
      { type: "p", text: "These are uncommon by volume but signal something specific you probably want to know about if you have a relevant watchlist:" },
      { type: "ul", items: [
        "152 — Recovery of Defaulted Student Loans. Spiked in 2025 with the Department of Education enforcement campaign.",
        "245 — Tort Product Liability. Mass-tort MDLs roll up here.",
        "362 — Personal Injury — Medical Malpractice.",
        "470 — RICO. Rare and consequential — every RICO complaint is a story.",
        "740 — Railway Labor Act. Tells you a strike or union dispute is now in court.",
        "871 — IRS — Third Party. Tax-collection disputes; useful for accounting + corporate-comms teams.",
      ]},
      { type: "pull", text: "RICO complaints are rare and consequential. Every one of them is a story." },
      { type: "h2", text: "How to filter on NOS in DocketLens" },
      { type: "p", text: "Three places it surfaces today:" },
      { type: "ul", items: [
        "Watchlist filter — add `natureOfSuitCodes: [\"830\", \"840\"]` to a watchlist and only patent-or-trade-secret matches count toward the alert.",
        "Saved search — the `?nos=850` URL param on /search filters in-page; same param threads through the saved-search RSS feed.",
        "REST API — `/api/v1/dockets?nos=410&date_from=2026-01-01` lets a programmatic consumer scan antitrust filings YTD.",
      ]},
      { type: "p", text: "If you want to see the full list, /jurisdictions lists every code we've encountered in the corpus along with how many active cases sit in it as of last refresh. We don't surface codes we've never seen — easier to keep the list relevant than comprehensive." },
      { type: "h2", text: "Where the taxonomy is going" },
      { type: "p", text: "The AO doesn't redesign this. Codes get added slowly (840 in 2016 was the last major addition). What's changing is how courts use them — some districts now require attorneys to pick the most-specific code rather than defaulting to the catch-all 190 / 890, which is gradually making the data more useful for the rest of us. We re-derive NOS distributions weekly so the shifts show up in /dashboard's heatmap without manual intervention." },
    ],
  },
  {
    slug: "three-months-in-the-metrics-we-stopped-publishing",
    title: "Three months in: the metrics we stopped publishing on /status, and the ones we added",
    excerpt:
      "When we launched /status we picked five service indicators that felt right. Three months of usage taught us that two of them were lying to us and one was being read backwards by ops.",
    tag: "Engineering",
    date: "2026-05-25",
    readMinutes: 6,
    author: "The DocketLens team",
    body: [
      { type: "p", text: "At launch our /status page had five indicators. Web app, REST API, ingest worker, AI summarization, email delivery, database. All green on launch day. That part was easy. The honest part — what we found out about each one over three months of running the service — is what this post is about." },
      { type: "h2", text: "What we stopped publishing" },
      { type: "p", text: "The first thing we cut was \"AI summarization\" as a binary status indicator. The thing it was measuring — whether Anthropic was up — is a Boolean question, but the user-facing experience isn't. When Anthropic returns 529s, we fall back to the cached summary the user saw twenty minutes ago. The page is functional. Setting that indicator to red would tell on-call to investigate when nothing in the product is actually broken. We replaced it with a `summary_freshness_p50` number: median age of the most recent summary shown across all org views. Anthropic outages move that number up by minutes, but nothing turns red until p50 crosses 90 minutes — which empirically only happens during a genuine multi-hour upstream outage." },
      { type: "p", text: "Second cut: email delivery. Resend has a stellar track record, so the indicator was always green. The signal we actually care about — \"are *our* emails getting through to inboxes\" — turns out to be different from \"is Resend up.\" We now track `digest_open_rate_24h` and `bounce_rate_24h` and alert on those instead of the upstream provider's status page. Twice this quarter both upstream indicators were green and our bounce rate doubled because of a subject-line change that triggered a Gmail filter heuristic. The provider status would have told us nothing." },
      { type: "pull", text: "Anthropic returning 529s isn't an outage if the page still works. Setting the indicator red would tell on-call to investigate when nothing in the product is actually broken." },
      { type: "h2", text: "What we added" },
      { type: "p", text: "Three new indicators replace the two cuts:" },
      { type: "ul", items: [
        "summary_freshness_p50 (and p95) — the median + 95th-percentile age of the most recent AI summary shown across all org views. Updates every 60 seconds. Pages red at p50 > 90m or p95 > 4h.",
        "match_to_alert_p50 — wall-clock from when a docket entry first lands in our DB to when a watchlist alert leaves our outbox. Includes the matcher, dispatch, and any rate-limit waits. Pages at p50 > 12s on Pro, 90s on Free.",
        "cl_pool_utilization — percentage of our pooled CourtListener token's daily budget consumed. Pages at >80%. We can do something useful when this trips (back-pressure, switch to BYO-token customers, ask FLP to raise). Provider-side rate-limit headers don't help if you're not watching them.",
      ]},
      { type: "h2", text: "The one indicator we kept but moved" },
      { type: "p", text: "\"Web app\" was always green and always will be. Vercel doesn't go down often enough for the indicator to be useful. We kept it because users *expect* a Web App green light on a status page — but we moved it to the bottom of the list and dropped it from the page-level summary. The summary now reads \"All systems operational\" when the four indicators that actually correlate with user pain are happy; the web-app light is informational." },
      { type: "h2", text: "What we learned about /status" },
      { type: "p", text: "Three months of running this taught us that a status page isn't documentation, it's an oncall input. The right indicators are the ones that go red when on-call should look, and stay green when they shouldn't. Every other framing — \"our users want to see five services\" — is a way of lying to yourself + your team about what matters. We will keep cutting indicators that don't predict pages and adding ones that do." },
      { type: "p", text: "Live status page: /status. Methodology + thresholds: linked from the page footer. As of today the page is, as the kids say, a real one." },
    ],
  },
  {
    slug: "building-vim-mode-for-a-timeline",
    title: "Building a vim mode for a timeline (and why we didn't use a library)",
    excerpt:
      "Our docket-detail page has 100+ entries. We added j/k/g/G/↓/↑ keyboard nav in ~80 lines and no dependencies. Here's the focus-management trick that did 80% of the work.",
    tag: "Engineering",
    date: "2026-05-25",
    readMinutes: 5,
    author: "The DocketLens team",
    body: [
      { type: "p", text: "Most patent dockets we surface have between 40 and 400 timeline entries. Scrolling through them with a trackpad is exactly the friction the product is supposed to remove. So we added vim-style keyboard navigation — `j` and `k` to move, `g`/`G` to jump to first/last, `/` to focus the page filter. Total wire: 110 lines in one client island. Total dependencies: zero. This is what we learned." },
      { type: "h2", text: "The naive approach (and why we didn't ship it)" },
      { type: "p", text: "The first idea was to track a `selectedIndex` in React state and re-render with a `bg-accent` highlight on the active row. Three problems with that: (1) re-rendering 100 rows on every keypress is wasteful, (2) `scrollIntoView` from React's render commit phase is racy, (3) the page navigates away when the user hits Enter — but our state has nothing to do with the browser's tab-order or screen-reader semantics. We'd be rebuilding focus management badly." },
      { type: "h2", text: "What we shipped instead" },
      { type: "p", text: "The real implementation walks the DOM, not React state. Every entry already renders with `id=\"ent_…\"` (it's part of the URL anchor format). On every keypress we query the DOM:" },
      { type: "ul", items: [
        "`document.querySelectorAll('li[id^=\"ent_\"]')` returns the current ordered list — naturally synced with what the user sees, no React state to drift.",
        "We track `currentIdx` in a closure inside `useEffect`, not React state. No re-render on arrow-key press.",
        "On `j` we call `target.setAttribute('tabindex', '-1')` then `target.focus({ preventScroll: true })` followed by `target.scrollIntoView({ behavior: 'smooth', block: 'center' })`. The order matters — focus must move before scroll so screen readers narrate the right row.",
        "`tabindex=-1` is set JIT (just-in-time) when we focus, NOT statically on every row. That means our keynav doesn't pollute the normal tab order — `Tab` still moves through interactive elements only.",
      ]},
      { type: "pull", text: "Focus must move before scroll so screen readers narrate the right row. tabindex=-1 set JIT, not statically, so Tab still flows through interactive elements only." },
      { type: "h2", text: "The skip-input check" },
      { type: "p", text: "Six lines of code at the top of the keydown handler save the user from a class of papercut bugs:" },
      { type: "ul", items: [
        "Check `document.activeElement.tagName` — bail out when it's `INPUT` or `TEXTAREA` so typing isn't hijacked.",
        "Check `.isContentEditable` — same reason, covers rich-text-editor frames.",
        "Check `e.metaKey || e.ctrlKey || e.altKey` — never fight browser shortcuts. ⌘J or ⌘K stay browser-native.",
      ]},
      { type: "p", text: "Most \"vim mode\" libraries we benchmarked skip at least one of these. The cmdk fork we initially evaluated did fight Cmd+Enter; that's why we wrote our own." },
      { type: "h2", text: "The one-time-hint pattern" },
      { type: "p", text: "First keypress shows a sonner toast: \"Use j/k or ↓/↑ to navigate.\" The next 99 keypresses don't. We persist a `dl-docket-keynav-seen` flag in localStorage; first read in `useEffect`, write on first keypress. Six lines. Discovers itself; doesn't nag." },
      { type: "h2", text: "When you'd actually want a library" },
      { type: "p", text: "If you need a full vim emulation — command mode, registers, macros — go use Monaco's vim binding or codemirror-vim. They've spent person-decades on edge cases ours hasn't seen. But for the \"j/k/g/G to walk a list, slash to filter\" subset, an 80-line file is faster to write than to learn an API." },
      { type: "p", text: "Source is in src/components/app/timeline-keyboard-nav.tsx — short enough to fit on one screen. Steal it. Or improve it and send a PR." },
    ],
  },
];
